# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Test'
    subscriptionId: '92fe876e-fd83-437e-ab74-2d7d72186221'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'cloud-shell-storage-centralindia'
    location: 'South India'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/saiswaroop22/ARM-Templates/main/StorageAccount/Azuredeploy.json'
    deploymentMode: 'Incremental'
